### ISSUE TITLE
It will not let me sign into my epic games account on Geforce 

### ISSUE THREAD

**Issue by ZbroE** [murar8/gfn-unlocker#12]
![Screenshot 2022-03-17 11 50 21 AM](https://user-images.githubusercontent.com/101829638/158875332-2df352bf-6688-4021-aefd-d7a51cf11026.png)

also when i was signed in it always gave me an error code

**Comment by murar8** [comment]
Sorry man but this extension does not really do anything apart from making the GFN servers think we are using a supported browser, so I wouldn't know how to help. One thing you could try is deleting all the site data and try again.
