### ISSUE TITLE
Chromium got blocked by Geforce Now

### ISSUE THREAD

**Issue by DarkevilPT** [murar8/gfn-unlocker#27]
Please halp!! :'D I cant play via chromium anymore.

**Comment by murar8** [comment]
Sorry man I'm not mantaining this extension anymore.

**Comment by DarkevilPT** [comment]
Do you know why I am saying this / its because I got a Radxa Rock 5B with
the purpose of running cloud games but it only supports ARM64 browsers ...
and Chrome Browser is not one of them yet.
