### ISSUE TITLE
mouse 

### ISSUE THREAD

**Issue by rodrigobbarros** [murar8/gfn-unlocker#3]
how can I resolve the delay in the mouse, or will this be my connection problem

**Comment by JacekJagosz** [comment]
Unfortunately this has nothing to do with this extension. Only thing this addon does is force GeforceNOW to work on unsupported browser.
Input lag is noticeably bigger with GFN than playing on local PC. That is influenced by how how high is your ping, which depends on your internet connection and physically how far away are the servers (e.g. closest servers to me are in Sweden, which is 1000km from me).
All you can try is different browser, trying it in official app in Windows or Android, or changing from WiFi to wired connection.
