### ISSUE TITLE
inactive agreement

### ISSUE THREAD

**Issue by T-Rey** [murar8/gfn-unlocker#4]
Hi

As soon as I go to the address of the GFN for chrome. A window of agreement with conditions pops up. I can follow the links inside the plate, but I cannot agree or close it.
Because of what the entire page is not available.

Link on which I go https://play.geforcenow.com/mall/#/layout/games
screenshot in attachment

![2](https://user-images.githubusercontent.com/75074054/100345223-ac082600-2fea-11eb-828b-92c4a53e5f5f.jpg)

**Comment by murar8** [comment]
Sorry, the extension is no longer necessary on chrome so it's most likely an issue with gfn.
