### ISSUE TITLE
Opera Gx

### ISSUE THREAD

**Issue by Panda123234** [murar8/gfn-unlocker#7]
Hello the unlocker is good but after the new opera gx update the unlocker isnt working can you fix it please?

**Comment by murar8** [comment]
Hi what does the error look like?

**Comment by Panda123234** [comment]
It just get a black screen 
![image_2021-10-09_150612](https://user-images.githubusercontent.com/84673013/136657158-287887e5-5384-40c9-98d8-5d1ac9fe04ec.png)

**Comment by murar8** [comment]
I'm sorry but that is a compatibility issue that I can't really do anything to fix. I would suggest you try playing on chrome which should have better support.
